# ==============================================================================
# 19_heatmap_corr_ages.R
# Author: Marcos Marín-Martín
# Date: 2026-02-09
# Description:
#   Age-Stratified Correlation Heatmap Generator.
#   Creates publication-quality heatmaps visualizing dendroclimatic correlations, 
#   specifically separated by Tree Age Groups (Young, Mid, Old).
#
#   Visualisation Details:
#   - Axes: X = Time Window (Months/Seasons), Y = Chronology Type (TRW, EW, LW, etc.).
#   - Color Scale: Diverging scale (Red-White-Blue/Yellow-Red) representing correlation strength.
#   - Significance: Filters non-significant correlations (p > 0.01) by masking them.
#   - Layout: Generates separate pages/files for each Age Group, combining multiple 
#     climate variables into a grid layout.
#
#   Inputs:
#   - Correlation Results File (generated by 16_main_correlations.R).
#
#   Outputs:
#   - Multi-panel PDF Heatmaps for each Age Group.
# ==============================================================================

# --- 0. Carga de Librerías ---
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(patchwork)

# --- PARÁMETROS A MODIFICAR ---
OUTPUT_DIR          <- 'PLACEHOLDER/path/to/input_output_dir'
CORRELATION_FILE    <- "correlation_results.txt"

SIGNIFICANCE_LEVEL  <- 0.01
# ------------------------------





# --- 1. Definición de Rutas y Parámetros Globales ---
correlation_file_path <- file.path(OUTPUT_DIR, CORRELATION_FILE)

if (!file.exists(correlation_file_path)) {
  stop(paste("El archivo de datos no se encontró en la ruta:", correlation_file_path))
}

# Parámetros de visualización
nonsignif_color <- "grey95"

# --- 1.1. PALETA DE COLORES BASE ---
cat("--- Definiendo la paleta de colores base ---\n")
color_neg_max <- "#083061"; color_zero <- "#FFFFFF"
positive_colors <- c("#ffffb2", "#ffeda0", "#FDE28A", "#FDE289", "#FDD774", "#FCC864", "#FBBA54", "#FBAE4A", "#FA9842", "#FA7836", "#F9582D", "#F64326", "#E31A1D", "#CF0E22", "#A50425", "#800226")

# Orden de variables
period_levels_monthly <- c(paste0("p", month.abb[10:12]), month.abb)
period_levels_extended <- c(period_levels_monthly, "DJF", "MAM", "JJA", "SON", "Annual")
chrono_type_levels_ordered <- c("TRW", "EW", "LW", "DBI", "EWBI", "LWBI")
climate_vars_classic <- c("precip", "tmax", "tmin")
spei_vars_ordered <- paste0("SPEI_", c(1, 3, 6, 12, 18, 24), "m")
all_climate_vars_ordered <- c(climate_vars_classic, spei_vars_ordered)
climate_var_titles <- c(precip = "Precipitation", tmax = "Max Temperature", tmin = "Min Temperature", SPEI_1m = "SPEI-1", SPEI_3m = "SPEI-3", SPEI_6m = "SPEI-6", SPEI_12m = "SPEI-12", SPEI_18m = "SPEI-18", SPEI_24m = "SPEI-24")

# --- 2. Carga y Preparación de los Datos ---
cat("--- Cargando y preparando los datos de correlación ---\n")
all_correlations_df <- read.table(correlation_file_path, header = TRUE, sep = "\t", stringsAsFactors = FALSE)

heatmap_data_prepared <- all_correlations_df %>%
  filter(period %in% period_levels_extended, climate_variable %in% all_climate_vars_ordered) %>%
  mutate(
    correlation_for_plot = ifelse(p_value < SIGNIFICANCE_LEVEL, correlation, NA_real_),
    age_group = factor(age_group, levels = c("yng", "mid", "old"), labels = c("Young", "Mid-Age", "Old")),
    chrono_type = factor(chrono_type, levels = rev(chrono_type_levels_ordered)),
    period = factor(period, levels = period_levels_extended),
    climate_variable = factor(climate_variable, levels = all_climate_vars_ordered)
  ) %>%
  filter(!is.na(age_group) & !is.na(chrono_type) & !is.na(climate_variable) & !is.na(period))

cat("Datos preparados.\n")

# --- 3. Generación de los Gráficos (Bucle por Grupo de Edad) ---
cat("--- Iniciando la generación de PDFs ---\n")

for (current_age_group in levels(heatmap_data_prepared$age_group)) {
  
  cat("  Generando heatmaps para el grupo de edad:", current_age_group, "\n")
  
  data_for_age_group <- heatmap_data_prepared %>% filter(age_group == current_age_group)
  if (nrow(data_for_age_group) == 0) {cat("    No hay datos para este grupo. Saltando...\n"); next}
  
  max_abs_corr <- max(abs(data_for_age_group$correlation), na.rm = TRUE)
  color_limit <- ceiling(max_abs_corr * 10) / 10
  
  # --- 3.1. DEFINICIÓN DEL MAPEO DE COLOR SIMÉTRICO ---
  final_colors <- c(color_neg_max, color_zero, color_zero, positive_colors)
  value_anchors_corr_scale <- c(-color_limit, -0.1, 0.1, seq(from = 0.1, to = color_limit, length.out = length(positive_colors)))
  final_values_rescaled <- scales::rescale(value_anchors_corr_scale, from = c(-color_limit, color_limit))
  
  # *** NUEVO: Definir los breaks para la leyenda ***
  all_possible_breaks <- seq(-1, 1, by = 0.2)
  legend_breaks <- round(all_possible_breaks[all_possible_breaks >= -color_limit & all_possible_breaks <= color_limit], 1)
  
  
  # Listas para guardar los plots
  classic_plots <- list(); spei_plots <- list()
  
  # TANDA 1: Plots climáticos clásicos
  for (current_clim_var in climate_vars_classic) {
    data_for_plot <- data_for_age_group %>% filter(climate_variable == current_clim_var)
    p <- ggplot(data_for_plot, aes(x = period, y = chrono_type, fill = correlation_for_plot)) +
      geom_tile(color = "grey80", linewidth = 0.4) +
      geom_vline(xintercept = length(period_levels_monthly) + 0.5, color = "gray50", linetype = "dashed") +
      scale_fill_gradientn(
        colors = final_colors, 
        values = final_values_rescaled, 
        limit = c(-color_limit, color_limit), 
        name = "Correlation (r)", 
        na.value = nonsignif_color,
        breaks = legend_breaks  # <-- AÑADIDO
      ) +
      labs(title = climate_var_titles[current_clim_var], x = NULL, y = NULL) +
      theme_minimal(base_size = 10) +
      theme(
        plot.title = element_text(hjust = 0.5, face = "bold", size = 12), 
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 9), 
        axis.text.y = element_text(face = "bold", size = 10), 
        legend.position = "right", 
        panel.grid = element_blank(),
        legend.key.height = unit(3.5, "cm"), # <-- AÑADIDO: Hace la leyenda más alta
        legend.key.width = unit(0.7, "cm")   # <-- AÑADIDO: Ajusta el ancho
      )
    classic_plots[[current_clim_var]] <- p
  }
  
  # TANDA 2: Plots de SPEI
  for (current_clim_var in spei_vars_ordered) {
    data_for_plot <- data_for_age_group %>% filter(climate_variable == current_clim_var, period %in% period_levels_monthly)
    p <- ggplot(data_for_plot, aes(x = period, y = chrono_type, fill = correlation_for_plot)) +
      geom_tile(color = "grey80", linewidth = 0.4) +
      scale_fill_gradientn(
        colors = final_colors, 
        values = final_values_rescaled, 
        limit = c(-color_limit, color_limit), 
        name = "Correlation (r)", 
        na.value = nonsignif_color,
        breaks = legend_breaks # <-- AÑADIDO
      ) +
      labs(title = climate_var_titles[current_clim_var], x = NULL, y = NULL) +
      theme_minimal(base_size = 10) +
      theme(
        plot.title = element_text(hjust = 0.5, face = "bold", size = 12), 
        axis.text.x = element_text(angle = 45, hjust = 1, size = 9), 
        axis.text.y = element_text(face = "bold", size = 10), 
        legend.position = "right", 
        panel.grid = element_blank(),
        legend.key.height = unit(3.5, "cm"), # <-- AÑADIDO
        legend.key.width = unit(0.7, "cm")   # <-- AÑADIDO
      )
    spei_plots[[current_clim_var]] <- p
  }
  
  if (length(classic_plots) == 3 && length(spei_plots) == 6) {
    top_row <- classic_plots[[1]] + classic_plots[[2]] + classic_plots[[3]]
    middle_row <- spei_plots[[1]] + spei_plots[[2]] + spei_plots[[3]]
    bottom_row <- spei_plots[[4]] + spei_plots[[5]] + spei_plots[[6]]
    
    combined_plot <- (top_row) / (middle_row) / (bottom_row) +
      plot_annotation(
        title = paste("Dendroclimatic Correlations for", current_age_group, "Trees"),
        subtitle = paste("Only p <", significance_level, "shown. Colors highlight |r| > 0.1."),
        theme = theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"), plot.subtitle = element_text(hjust = 0.5, size = 12, color = "gray30"))
      ) +
      plot_layout(guides = 'collect') & theme(legend.position = 'right')
    
    pdf_filename <- file.path(OUTPUT_DIR, paste0("Heatmaps_Correlations_", gsub("-", "", current_age_group), ".pdf"))
    
    ggsave(filename = pdf_filename, plot = combined_plot, width = 14, height = 14, units = "in", device = "pdf")
    
    cat("    PDF con leyenda final guardado en:", pdf_filename, "\n")
  } else {
    cat("    No se pudieron generar todos los plots para", current_age_group, ". Saltando guardado de PDF.\n")
  }
}

cat("\n--- Proceso completado ---\n")
