# ==============================================================================
# 20_heatmap_corr_ages_joint.R
# Author: Marcos Marín-Martín
# Date: 2026-02-09
# Description:
#   Joint Age-Group Correlation Panel (A4 Poster).
#   An advanced visualisation script that stitches together correlation heatmaps 
#   for ALL Age Groups into a single, massive A4-sised panel.
#
#   Layout:
#   - Rows: Age Groups (Young, Mid, Old).
#   - Columns: Climate Variables (Precip, Tmax, Tmin, SPEI scales).
#   - Shared Legend: Ensures comparability across all panels.
#   - Aesthetics: Clean, minimal theme suitable for posters or supplemental material.
#
#   Inputs:
#   - Correlation Results File (generated by 16_main_correlations.R).
#
#   Outputs:
#   - A single A4 PDF file containing the comprehensive comparative panel.
# ==============================================================================

# --- 0. Carga de Librerías ---
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
library(patchwork)

# --- PARÁMETROS A MODIFICAR ---
OUTPUT_DIR          <- 'PLACEHOLDER/path/to/input_output_dir'
CORRELATION_FILE    <- "correlation_results.txt"

SIGNIFICANCE_LEVEL  <- 0.01
# ------------------------------




# --- 1. Definición de Rutas y Parámetros Globales ---
correlation_file_path <- file.path(OUTPUT_DIR, CORRELATION_FILE)

if (!file.exists(correlation_file_path)) {
  stop(paste("El archivo de datos no se encontró en la ruta:", correlation_file_path))
}

# Parámetros de visualización y paleta de colores
nonsignif_color <- "grey95"
color_neg_max <- "#083061"; color_zero <- "#FFFFFF"
positive_colors <- c("#ffffb2", "#ffeda0", "#FDE28A", "#FDE289", "#FDD774", "#FCC864", "#FBBA54", "#FBAE4A", "#FA9842", "#FA7836", "#F9582D", "#F64326", "#E31A1D", "#CF0E22", "#A50425", "#800226")

# Orden de variables
period_levels_monthly <- c(paste0("p", month.abb[10:12]), month.abb)
period_levels_extended <- c(period_levels_monthly, "DJF", "MAM", "JJA", "SON", "Annual")
chrono_type_levels_ordered <- c("TRW", "EW", "LW", "DBI", "EWBI", "LWBI")
# *** NUEVO ORDEN DE VARIABLES CLIMÁTICAS ***
climate_vars_classic <- c("tmax", "tmin", "precip") 
spei_vars_ordered <- paste0("SPEI_", c(1, 3, 6, 12, 18, 24), "m")
all_climate_vars_ordered <- c(climate_vars_classic, spei_vars_ordered)
climate_var_titles <- c(precip = "Precipitation", tmax = "Max Temp.", tmin = "Min Temp.", SPEI_1m = "SPEI-1", SPEI_3m = "SPEI-3", SPEI_6m = "SPEI-6", SPEI_12m = "SPEI-12", SPEI_18m = "SPEI-18", SPEI_24m = "SPEI-24")

# Crear subconjuntos de etiquetas para el eje X
breaks_step <- 2
breaks_extended_thinned <- period_levels_extended[seq(1, length(period_levels_extended), by = breaks_step)]
breaks_monthly_thinned <- period_levels_monthly[seq(1, length(period_levels_monthly), by = breaks_step)]

# --- 2. Carga y Preparación de los Datos ---
cat("--- Cargando y preparando los datos de correlación ---\n")
all_correlations_df <- read.table(correlation_file_path, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
heatmap_data_prepared <- all_correlations_df %>%
  filter(period %in% period_levels_extended, climate_variable %in% all_climate_vars_ordered) %>%
  mutate(
    correlation_for_plot = ifelse(p_value < SIGNIFICANCE_LEVEL, correlation, NA_real_),
    age_group = factor(age_group, levels = c("yng", "mid", "old"), labels = c("Young", "Mid-Age", "Old")),
    chrono_type = factor(chrono_type, levels = rev(chrono_type_levels_ordered)),
    period = factor(period, levels = period_levels_extended),
    climate_variable = factor(climate_variable, levels = all_climate_vars_ordered)
  ) %>%
  filter(!is.na(age_group) & !is.na(chrono_type) & !is.na(climate_variable) & !is.na(period))
cat("Datos preparados.\n")

# --- 3. CÁLCULO DE LA ESCALA DE COLOR GLOBAL ---
cat("--- Calculando la escala de color global ---\n")
max_abs_corr <- max(abs(heatmap_data_prepared$correlation), na.rm = TRUE)
color_limit <- ceiling(max_abs_corr * 10) / 10
final_colors <- c(color_neg_max, color_zero, color_zero, positive_colors)
value_anchors_corr_scale <- c(-color_limit, -0.1, 0.1, seq(from = 0.1, to = color_limit, length.out = length(positive_colors)))
final_values_rescaled <- scales::rescale(value_anchors_corr_scale, from = c(-color_limit, color_limit))
all_possible_breaks <- seq(-1, 1, by = 0.2)
legend_breaks <- round(all_possible_breaks[all_possible_breaks >= -color_limit & all_possible_breaks <= color_limit], 1)

# --- 4. GENERACIÓN DE TODOS LOS 27 PLOTS EN MEMORIA ---
cat("--- Generando los 27 heatmaps individuales en memoria ---\n")
all_plots <- list()

for (current_age_group in levels(heatmap_data_prepared$age_group)) {
  all_plots[[current_age_group]] <- list()
  
  # Plots climáticos clásicos (eje X extendido)
  for (current_clim_var in climate_vars_classic) {
    data_for_plot <- heatmap_data_prepared %>% filter(age_group == current_age_group, climate_variable == current_clim_var)
    p <- ggplot(data_for_plot, aes(x = period, y = chrono_type, fill = correlation_for_plot)) +
      geom_tile(color = "grey80", linewidth = 0.2) +
      geom_vline(xintercept = length(period_levels_monthly) + 0.5, color = "gray50", linetype = "dashed", linewidth=0.3) +
      scale_fill_gradientn(colors = final_colors, values = final_values_rescaled, limit = c(-color_limit, color_limit), name = "r", na.value = nonsignif_color, breaks = legend_breaks) +
      scale_x_discrete(breaks = breaks_extended_thinned, drop = FALSE) +
      labs(x = NULL, y = NULL) +
      theme_minimal(base_size = 7) +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), panel.grid = element_blank())
    all_plots[[current_age_group]][[current_clim_var]] <- p
  }
  
  # Plots de SPEI (eje X mensual)
  for (current_clim_var in spei_vars_ordered) {
    data_for_plot <- heatmap_data_prepared %>% filter(age_group == current_age_group, climate_variable == current_clim_var, period %in% period_levels_monthly)
    p <- ggplot(data_for_plot, aes(x = period, y = chrono_type, fill = correlation_for_plot)) +
      geom_tile(color = "grey80", linewidth = 0.2) +
      scale_fill_gradientn(colors = final_colors, values = final_values_rescaled, limit = c(-color_limit, color_limit), name = "r", na.value = nonsignif_color, breaks = legend_breaks) +
      scale_x_discrete(breaks = breaks_monthly_thinned, drop = FALSE) +
      labs(x = NULL, y = NULL) +
      theme_minimal(base_size = 7) + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), panel.grid = element_blank())
    all_plots[[current_age_group]][[current_clim_var]] <- p
  }
}
cat("Todos los heatmaps generados.\n")

# --- 5. ENSAMBLAJE DEL PANEL COMPARATIVO A4 ---
cat("--- Ensamblando el panel comparativo final ---\n")

# Reordenar la lista de plots para que sea más fácil de acceder
plots_ordered_list <- lapply(levels(heatmap_data_prepared$age_group), function(age) {
  lapply(all_climate_vars_ordered, function(clim) all_plots[[age]][[clim]])
})

# Añadir los títulos de las variables SOLO a la primera fila de plots
plots_row_young_with_titles <- lapply(seq_along(all_climate_vars_ordered), function(i) {
  plots_ordered_list[[1]][[i]] + 
    labs(title = climate_var_titles[all_climate_vars_ordered[i]]) +
    theme(plot.title = element_text(size = 8, face = "bold", hjust = 0.5))
})

# Ensamblar las filas
row_young <- wrap_plots(plots_row_young_with_titles, ncol = 9)
row_mid   <- wrap_plots(plots_ordered_list[[2]], ncol = 9)
row_old   <- wrap_plots(plots_ordered_list[[3]], ncol = 9)

# Etiquetas de las filas (grupos de edad)
label_young <- ggplot() + annotate("text", x=1, y=1, label="Young", angle=90, size=5, fontface="bold") + theme_void()
label_mid   <- ggplot() + annotate("text", x=1, y=1, label="Mid-Age", angle=90, size=5, fontface="bold") + theme_void()
label_old   <- ggplot() + annotate("text", x=1, y=1, label="Old", angle=90, size=5, fontface="bold") + theme_void()

# Combinar las etiquetas con sus respectivas filas de plots
full_row_young <- label_young + row_young + plot_layout(widths = c(1, 40))
full_row_mid   <- label_mid   + row_mid   + plot_layout(widths = c(1, 40))
full_row_old   <- label_old   + row_old   + plot_layout(widths = c(1, 40))

# Combinar las tres filas verticalmente
final_plot <- full_row_young / full_row_mid / full_row_old

# Añadir un título general y una única leyenda compartida
final_plot_annotated <- final_plot + 
  plot_annotation(
    title = "Dendroclimatic Correlation Analysis Across Age Groups",
    subtitle = paste("Only significant correlations (p <", significance_level, ") are colored. White indicates non-significant or |r| < 0.1."),
    theme = theme(
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
      plot.subtitle = element_text(hjust = 0.5, size = 10, color = "gray30")
    )
  ) +
  plot_layout(guides = 'collect') & theme(legend.position = 'right', legend.key.height = unit(2.5, "cm"))

# --- 6. GUARDAR EL PDF FINAL ---
output_filename <- file.path(OUTPUT_DIR, "Heatmaps_Correlations_AllAges_A4.pdf")
cat("--- Guardando el panel comparativo final en:", output_filename, "---\n")

ggsave(
  filename = output_filename,
  plot = final_plot_annotated,
  width = 297, # A4 landscape width
  height = 210, # A4 landscape height
  units = "mm",
  device = "pdf",
  limitsize = FALSE
)

cat("\n--- Proceso completado ---\n")
